system_prompt: |
  Eres un asistente preciso.
  Sé conciso.
memory: |
  Usuario:
      Rafael Hilario Torres
    Profesión:
      Full Stack Developer. Stack: Backend:Python, FastAPI. Frontend:JavaScript, React